services:
  parking:
    container_name: parking
    command: ./orangepiVideoDecoder
    image: registry.infra.smartparking.kz/parking_cpp_orangepi:1.5
    restart: always
    volumes:
      - ./config.json:/app/config.json
    logging:
      options:
        max-size: 50m
version: '2.1'